// Code generated by MockGen. DO NOT EDIT.
// Source: internal/payments/payments.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	stripe "github.com/stripe/stripe-go/v79"
)

// MockPayment is a mock of Payment interface.
type MockPayment struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMockRecorder
}

// MockPaymentMockRecorder is the mock recorder for MockPayment.
type MockPaymentMockRecorder struct {
	mock *MockPayment
}

// NewMockPayment creates a new mock instance.
func NewMockPayment(ctrl *gomock.Controller) *MockPayment {
	mock := &MockPayment{ctrl: ctrl}
	mock.recorder = &MockPaymentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayment) EXPECT() *MockPaymentMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockPayment) CreateCustomer(name, email, phone string) (*stripe.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", name, email, phone)
	ret0, _ := ret[0].(*stripe.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockPaymentMockRecorder) CreateCustomer(name, email, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockPayment)(nil).CreateCustomer), name, email, phone)
}

// DeleteCustomer mocks base method.
func (m *MockPayment) DeleteCustomer(customerID string) (*stripe.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", customerID)
	ret0, _ := ret[0].(*stripe.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockPaymentMockRecorder) DeleteCustomer(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockPayment)(nil).DeleteCustomer), customerID)
}
